/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/log_items": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_items.id"];
          created_at?: parameters["rowFilter.log_items.created_at"];
          updated_at?: parameters["rowFilter.log_items.updated_at"];
          title?: parameters["rowFilter.log_items.title"];
          date?: parameters["rowFilter.log_items.date"];
          group?: parameters["rowFilter.log_items.group"];
          ended_at?: parameters["rowFilter.log_items.ended_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["log_items"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** log_items */
          log_items?: definitions["log_items"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_items.id"];
          created_at?: parameters["rowFilter.log_items.created_at"];
          updated_at?: parameters["rowFilter.log_items.updated_at"];
          title?: parameters["rowFilter.log_items.title"];
          date?: parameters["rowFilter.log_items.date"];
          group?: parameters["rowFilter.log_items.group"];
          ended_at?: parameters["rowFilter.log_items.ended_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_items.id"];
          created_at?: parameters["rowFilter.log_items.created_at"];
          updated_at?: parameters["rowFilter.log_items.updated_at"];
          title?: parameters["rowFilter.log_items.title"];
          date?: parameters["rowFilter.log_items.date"];
          group?: parameters["rowFilter.log_items.group"];
          ended_at?: parameters["rowFilter.log_items.ended_at"];
        };
        body: {
          /** log_items */
          log_items?: definitions["log_items"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/log_groups": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_groups.id"];
          created_at?: parameters["rowFilter.log_groups.created_at"];
          updated_at?: parameters["rowFilter.log_groups.updated_at"];
          title?: parameters["rowFilter.log_groups.title"];
          rank?: parameters["rowFilter.log_groups.rank"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["log_groups"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** log_groups */
          log_groups?: definitions["log_groups"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_groups.id"];
          created_at?: parameters["rowFilter.log_groups.created_at"];
          updated_at?: parameters["rowFilter.log_groups.updated_at"];
          title?: parameters["rowFilter.log_groups.title"];
          rank?: parameters["rowFilter.log_groups.rank"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.log_groups.id"];
          created_at?: parameters["rowFilter.log_groups.created_at"];
          updated_at?: parameters["rowFilter.log_groups.updated_at"];
          title?: parameters["rowFilter.log_groups.title"];
          rank?: parameters["rowFilter.log_groups.rank"];
        };
        body: {
          /** log_groups */
          log_groups?: definitions["log_groups"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  log_items: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: text */
    title: string;
    /** Format: date */
    date: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `log_groups.id`.<fk table='log_groups' column='id'/>
     */
    group: number;
    /** Format: timestamp with time zone */
    ended_at?: string;
  };
  log_groups: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: text */
    title: string;
    /** Format: smallint */
    rank: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description log_items */
  "body.log_items": definitions["log_items"];
  /** Format: bigint */
  "rowFilter.log_items.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.log_items.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.log_items.updated_at": string;
  /** Format: text */
  "rowFilter.log_items.title": string;
  /** Format: date */
  "rowFilter.log_items.date": string;
  /** Format: bigint */
  "rowFilter.log_items.group": string;
  /** Format: timestamp with time zone */
  "rowFilter.log_items.ended_at": string;
  /** @description log_groups */
  "body.log_groups": definitions["log_groups"];
  /** Format: bigint */
  "rowFilter.log_groups.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.log_groups.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.log_groups.updated_at": string;
  /** Format: text */
  "rowFilter.log_groups.title": string;
  /** Format: smallint */
  "rowFilter.log_groups.rank": string;
}

export interface operations {}

export interface external {}
