// Generated by gen-photo-variants.ts — rerun after adding photos (pnpm gen-photos)
const photoMeta: Record<string, { w: number; h: number; srcset: string }> = {
  "/posts/2026-0926-bangkok-flood-01-prachaniwet-market.webp": {
    w: 800,
    h: 533,
    srcset:
      "/posts/2026-0926-bangkok-flood-01-prachaniwet-market.640w.webp 640w, /posts/2026-0926-bangkok-flood-01-prachaniwet-market.webp 800w",
  },
  "/posts/2026-0926-bangkok-flood-02-nawamin-road.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2026-0926-bangkok-flood-02-nawamin-road.640w.webp 640w, /posts/2026-0926-bangkok-flood-02-nawamin-road.960w.webp 960w, /posts/2026-0926-bangkok-flood-02-nawamin-road.webp 1280w",
  },
  "/posts/2026-0926-bangkok-flood-03-phahon-yothin.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2026-0926-bangkok-flood-03-phahon-yothin.640w.webp 640w, /posts/2026-0926-bangkok-flood-03-phahon-yothin.960w.webp 960w, /posts/2026-0926-bangkok-flood-03-phahon-yothin.webp 1280w",
  },
  "/posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.640w.webp 640w, /posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.960w.webp 960w, /posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.webp 1280w",
  },
  "/posts/2026-0926-bangkok-flood-05-lat-phrao-41.webp": {
    w: 1280,
    h: 1707,
    srcset:
      "/posts/2026-0926-bangkok-flood-05-lat-phrao-41.640w.webp 640w, /posts/2026-0926-bangkok-flood-05-lat-phrao-41.960w.webp 960w, /posts/2026-0926-bangkok-flood-05-lat-phrao-41.webp 1280w",
  },
  "/posts/2026-0926-bangkok-flood-08-hero.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2026-0926-bangkok-flood-08-hero.640w.webp 640w, /posts/2026-0926-bangkok-flood-08-hero.960w.webp 960w, /posts/2026-0926-bangkok-flood-08-hero.webp 1280w",
  },
  "/posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.640w.webp 640w, /posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.960w.webp 960w, /posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.webp 1200w",
  },
  "/posts/2026-0926-bangkok-flood-11-phetchaburi-wading.webp": {
    w: 850,
    h: 567,
    srcset:
      "/posts/2026-0926-bangkok-flood-11-phetchaburi-wading.640w.webp 640w, /posts/2026-0926-bangkok-flood-11-phetchaburi-wading.webp 850w",
  },
  "/posts/2026-0926-bangkok-flood-12-phetchaburi-scene.webp": {
    w: 850,
    h: 567,
    srcset:
      "/posts/2026-0926-bangkok-flood-12-phetchaburi-scene.640w.webp 640w, /posts/2026-0926-bangkok-flood-12-phetchaburi-scene.webp 850w",
  },
  "/posts/2026-0926-bangkok-flood-13-bangkapi-community.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-13-bangkapi-community.640w.webp 640w, /posts/2026-0926-bangkok-flood-13-bangkapi-community.960w.webp 960w, /posts/2026-0926-bangkok-flood-13-bangkapi-community.webp 1200w",
  },
  "/posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.webp": {
    w: 850,
    h: 550,
    srcset:
      "/posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.640w.webp 640w, /posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.webp 850w",
  },
  "/posts/2026-0926-bangkok-flood-15-muang-thong-thani.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-15-muang-thong-thani.640w.webp 640w, /posts/2026-0926-bangkok-flood-15-muang-thong-thani.960w.webp 960w, /posts/2026-0926-bangkok-flood-15-muang-thong-thani.webp 1200w",
  },
  "/posts/2026-0926-bangkok-flood-16-pm-boat-relief.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-16-pm-boat-relief.640w.webp 640w, /posts/2026-0926-bangkok-flood-16-pm-boat-relief.960w.webp 960w, /posts/2026-0926-bangkok-flood-16-pm-boat-relief.webp 1200w",
  },
  "/posts/2026-0926-bangkok-flood-17-market-wading.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-17-market-wading.640w.webp 640w, /posts/2026-0926-bangkok-flood-17-market-wading.960w.webp 960w, /posts/2026-0926-bangkok-flood-17-market-wading.webp 1200w",
  },
  "/posts/2026-0926-bangkok-flood-18-tmd-forecast.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2026-0926-bangkok-flood-18-tmd-forecast.640w.webp 640w, /posts/2026-0926-bangkok-flood-18-tmd-forecast.960w.webp 960w, /posts/2026-0926-bangkok-flood-18-tmd-forecast.webp 1280w",
  },
};

export default photoMeta;
