// Generated by gen-photo-variants.ts — rerun after adding photos (pnpm gen-photos)
const photoMeta: Record<
  string,
  { w: number; h: number; srcset: string; sizes: string }
> = {
  "/posts/2023-0110-1st-pr-to-famous-repo-bot-1.webp": {
    w: 1000,
    h: 757,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-bot-1.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-bot-1.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-bot-1.webp 1000w",
    sizes:
      "(min-width: 1024px) 396px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-bot-2.webp": {
    w: 1000,
    h: 149,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-bot-2.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-bot-2.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-bot-2.webp 1000w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-merge.webp": {
    w: 1000,
    h: 290,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-merge.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-merge.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-merge.webp 1000w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-owner-approval.webp": {
    w: 1000,
    h: 142,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-owner-approval.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-owner-approval.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-owner-approval.webp 1000w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-pr-description.webp": {
    w: 1000,
    h: 520,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-pr-description.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-pr-description.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-pr-description.webp 1000w",
    sizes:
      "(min-width: 1024px) 577px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-ready-to-merge.webp": {
    w: 1000,
    h: 432,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-ready-to-merge.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-ready-to-merge.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-ready-to-merge.webp 1000w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2023-0110-1st-pr-to-famous-repo-upgrade-pr.webp": {
    w: 1000,
    h: 436,
    srcset:
      "/posts/2023-0110-1st-pr-to-famous-repo-upgrade-pr.640w.webp 640w, /posts/2023-0110-1st-pr-to-famous-repo-upgrade-pr.960w.webp 960w, /posts/2023-0110-1st-pr-to-famous-repo-upgrade-pr.webp 1000w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2024-1110-theres-no-such-thing-as-an-easy-job.webp": {
    w: 1280,
    h: 1707,
    srcset:
      "/posts/2024-1110-theres-no-such-thing-as-an-easy-job.640w.webp 640w, /posts/2024-1110-theres-no-such-thing-as-an-easy-job.960w.webp 960w, /posts/2024-1110-theres-no-such-thing-as-an-easy-job.webp 1280w",
    sizes:
      "(min-width: 1024px) 225px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0204-predictably-irrational.webp": {
    w: 1179,
    h: 2096,
    srcset:
      "/posts/2025-0204-predictably-irrational.640w.webp 640w, /posts/2025-0204-predictably-irrational.960w.webp 960w, /posts/2025-0204-predictably-irrational.webp 1179w",
    sizes:
      "(min-width: 1024px) 169px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0208-granblue-fantasy-relink.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2025-0208-granblue-fantasy-relink.640w.webp 640w, /posts/2025-0208-granblue-fantasy-relink.960w.webp 960w, /posts/2025-0208-granblue-fantasy-relink.webp 1280w",
    sizes:
      "(min-width: 1024px) 400px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0209-docker-and-kubernetes-the-complete-guide.webp": {
    w: 1280,
    h: 865,
    srcset:
      "/posts/2025-0209-docker-and-kubernetes-the-complete-guide.640w.webp 640w, /posts/2025-0209-docker-and-kubernetes-the-complete-guide.960w.webp 960w, /posts/2025-0209-docker-and-kubernetes-the-complete-guide.webp 1280w",
    sizes:
      "(min-width: 1024px) 444px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0209-the-selfish-gene.webp": {
    w: 1280,
    h: 721,
    srcset:
      "/posts/2025-0209-the-selfish-gene.640w.webp 640w, /posts/2025-0209-the-selfish-gene.960w.webp 960w, /posts/2025-0209-the-selfish-gene.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0214-doubt.webp": {
    w: 1200,
    h: 1714,
    srcset:
      "/posts/2025-0214-doubt.640w.webp 640w, /posts/2025-0214-doubt.960w.webp 960w, /posts/2025-0214-doubt.webp 1200w",
    sizes:
      "(min-width: 1024px) 210px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0222-the-better-angels-of-our-nature.webp": {
    w: 963,
    h: 1699,
    srcset:
      "/posts/2025-0222-the-better-angels-of-our-nature.640w.webp 640w, /posts/2025-0222-the-better-angels-of-our-nature.960w.webp 960w, /posts/2025-0222-the-better-angels-of-our-nature.webp 963w",
    sizes:
      "(min-width: 1024px) 170px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0222-the-wedding-people.webp": {
    w: 963,
    h: 1699,
    srcset:
      "/posts/2025-0222-the-wedding-people.640w.webp 640w, /posts/2025-0222-the-wedding-people.960w.webp 960w, /posts/2025-0222-the-wedding-people.webp 963w",
    sizes:
      "(min-width: 1024px) 170px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0223-udemy-github-copilot.webp": {
    w: 658,
    h: 512,
    srcset:
      "/posts/2025-0223-udemy-github-copilot.640w.webp 640w, /posts/2025-0223-udemy-github-copilot.webp 658w",
    sizes:
      "(min-width: 1024px) 386px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0305-gi-bad.webp": {
    w: 1280,
    h: 1707,
    srcset:
      "/posts/2025-0305-gi-bad.640w.webp 640w, /posts/2025-0305-gi-bad.960w.webp 960w, /posts/2025-0305-gi-bad.webp 1280w",
    sizes:
      "(min-width: 1024px) 225px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0307-his-three-daughters.webp": {
    w: 851,
    h: 479,
    srcset:
      "/posts/2025-0307-his-three-daughters.640w.webp 640w, /posts/2025-0307-his-three-daughters.webp 851w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0311-dont-move.webp": {
    w: 1280,
    h: 640,
    srcset:
      "/posts/2025-0311-dont-move.640w.webp 640w, /posts/2025-0311-dont-move.960w.webp 960w, /posts/2025-0311-dont-move.webp 1280w",
    sizes:
      "(min-width: 1024px) 600px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0311-zzz-agents.webp": {
    w: 1280,
    h: 591,
    srcset:
      "/posts/2025-0311-zzz-agents.640w.webp 640w, /posts/2025-0311-zzz-agents.960w.webp 960w, /posts/2025-0311-zzz-agents.webp 1280w",
    sizes:
      "(min-width: 1024px) 650px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0311-zzz-dashboard.webp": {
    w: 1280,
    h: 591,
    srcset:
      "/posts/2025-0311-zzz-dashboard.640w.webp 640w, /posts/2025-0311-zzz-dashboard.960w.webp 960w, /posts/2025-0311-zzz-dashboard.webp 1280w",
    sizes:
      "(min-width: 1024px) 650px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0311-zzz-team.webp": {
    w: 1280,
    h: 591,
    srcset:
      "/posts/2025-0311-zzz-team.640w.webp 640w, /posts/2025-0311-zzz-team.960w.webp 960w, /posts/2025-0311-zzz-team.webp 1280w",
    sizes:
      "(min-width: 1024px) 650px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0313-spaceman.webp": {
    w: 1280,
    h: 666,
    srcset:
      "/posts/2025-0313-spaceman.640w.webp 640w, /posts/2025-0313-spaceman.960w.webp 960w, /posts/2025-0313-spaceman.webp 1280w",
    sizes:
      "(min-width: 1024px) 577px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0317-udemy-procreate.webp": {
    w: 654,
    h: 522,
    srcset:
      "/posts/2025-0317-udemy-procreate.640w.webp 640w, /posts/2025-0317-udemy-procreate.webp 654w",
    sizes:
      "(min-width: 1024px) 376px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0319-the-autopsy-of-jane-doe.webp": {
    w: 700,
    h: 1037,
    srcset:
      "/posts/2025-0319-the-autopsy-of-jane-doe.640w.webp 640w, /posts/2025-0319-the-autopsy-of-jane-doe.webp 700w",
    sizes:
      "(min-width: 1024px) 203px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0321-in-youth-we-trust.webp": {
    w: 1280,
    h: 672,
    srcset:
      "/posts/2025-0321-in-youth-we-trust.640w.webp 640w, /posts/2025-0321-in-youth-we-trust.960w.webp 960w, /posts/2025-0321-in-youth-we-trust.webp 1280w",
    sizes:
      "(min-width: 1024px) 571px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0321-nanglen-thee-boy-1.webp": {
    w: 1280,
    h: 946,
    srcset:
      "/posts/2025-0321-nanglen-thee-boy-1.640w.webp 640w, /posts/2025-0321-nanglen-thee-boy-1.960w.webp 960w, /posts/2025-0321-nanglen-thee-boy-1.webp 1280w",
    sizes:
      "(min-width: 1024px) 406px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0321-nanglen-thee-boy-2.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0321-nanglen-thee-boy-2.640w.webp 640w, /posts/2025-0321-nanglen-thee-boy-2.960w.webp 960w, /posts/2025-0321-nanglen-thee-boy-2.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0321-nanglen-thee-boy-3.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0321-nanglen-thee-boy-3.640w.webp 640w, /posts/2025-0321-nanglen-thee-boy-3.960w.webp 960w, /posts/2025-0321-nanglen-thee-boy-3.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0321-nanglen-thee-boy-4.webp": {
    w: 1024,
    h: 576,
    srcset:
      "/posts/2025-0321-nanglen-thee-boy-4.640w.webp 640w, /posts/2025-0321-nanglen-thee-boy-4.960w.webp 960w, /posts/2025-0321-nanglen-thee-boy-4.webp 1024w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0328-adolescence.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2025-0328-adolescence.640w.webp 640w, /posts/2025-0328-adolescence.960w.webp 960w, /posts/2025-0328-adolescence.webp 1280w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0402-solo-leveling-s2.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2025-0402-solo-leveling-s2.640w.webp 640w, /posts/2025-0402-solo-leveling-s2.960w.webp 960w, /posts/2025-0402-solo-leveling-s2.webp 1280w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0404-the-hot-spot.webp": {
    w: 1200,
    h: 800,
    srcset:
      "/posts/2025-0404-the-hot-spot.640w.webp 640w, /posts/2025-0404-the-hot-spot.960w.webp 960w, /posts/2025-0404-the-hot-spot.webp 1200w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0412-udemy-rest-api-design-development-management.webp": {
    w: 640,
    h: 506,
    srcset:
      "/posts/2025-0412-udemy-rest-api-design-development-management.webp 640w",
    sizes:
      "(min-width: 1024px) 379px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0414-mh-wilds-1.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0414-mh-wilds-1.640w.webp 640w, /posts/2025-0414-mh-wilds-1.960w.webp 960w, /posts/2025-0414-mh-wilds-1.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0414-mh-wilds-2.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0414-mh-wilds-2.640w.webp 640w, /posts/2025-0414-mh-wilds-2.960w.webp 960w, /posts/2025-0414-mh-wilds-2.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0414-mh-wilds-3.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0414-mh-wilds-3.640w.webp 640w, /posts/2025-0414-mh-wilds-3.960w.webp 960w, /posts/2025-0414-mh-wilds-3.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0414-mh-wilds-4.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0414-mh-wilds-4.640w.webp 640w, /posts/2025-0414-mh-wilds-4.960w.webp 960w, /posts/2025-0414-mh-wilds-4.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0414-mh-wilds-5.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2025-0414-mh-wilds-5.640w.webp 640w, /posts/2025-0414-mh-wilds-5.960w.webp 960w, /posts/2025-0414-mh-wilds-5.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0415-black-mirror-7.webp": {
    w: 1280,
    h: 641,
    srcset:
      "/posts/2025-0415-black-mirror-7.640w.webp 640w, /posts/2025-0415-black-mirror-7.960w.webp 960w, /posts/2025-0415-black-mirror-7.webp 1280w",
    sizes:
      "(min-width: 1024px) 599px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0418-project-hail-mary.webp": {
    w: 1071,
    h: 1904,
    srcset:
      "/posts/2025-0418-project-hail-mary.640w.webp 640w, /posts/2025-0418-project-hail-mary.960w.webp 960w, /posts/2025-0418-project-hail-mary.webp 1071w",
    sizes:
      "(min-width: 1024px) 169px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0419-jules.webp": {
    w: 1280,
    h: 640,
    srcset:
      "/posts/2025-0419-jules.640w.webp 640w, /posts/2025-0419-jules.960w.webp 960w, /posts/2025-0419-jules.webp 1280w",
    sizes:
      "(min-width: 1024px) 600px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0423-the-natural-cat.webp": {
    w: 1155,
    h: 1539,
    srcset:
      "/posts/2025-0423-the-natural-cat.640w.webp 640w, /posts/2025-0423-the-natural-cat.960w.webp 960w, /posts/2025-0423-the-natural-cat.webp 1155w",
    sizes:
      "(min-width: 1024px) 225px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0427-you-5.webp": {
    w: 1200,
    h: 1778,
    srcset:
      "/posts/2025-0427-you-5.640w.webp 640w, /posts/2025-0427-you-5.960w.webp 960w, /posts/2025-0427-you-5.webp 1200w",
    sizes:
      "(min-width: 1024px) 202px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0505-the-art-of-procrastination.webp": {
    w: 1008,
    h: 1344,
    srcset:
      "/posts/2025-0505-the-art-of-procrastination.640w.webp 640w, /posts/2025-0505-the-art-of-procrastination.960w.webp 960w, /posts/2025-0505-the-art-of-procrastination.webp 1008w",
    sizes:
      "(min-width: 1024px) 225px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0531-mad-unicorn.webp": {
    w: 1280,
    h: 638,
    srcset:
      "/posts/2025-0531-mad-unicorn.640w.webp 640w, /posts/2025-0531-mad-unicorn.960w.webp 960w, /posts/2025-0531-mad-unicorn.webp 1280w",
    sizes:
      "(min-width: 1024px) 602px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0614-earthlings.webp": {
    w: 1010,
    h: 1500,
    srcset:
      "/posts/2025-0614-earthlings.640w.webp 640w, /posts/2025-0614-earthlings.960w.webp 960w, /posts/2025-0614-earthlings.webp 1010w",
    sizes:
      "(min-width: 1024px) 202px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0701-squid-game-3.webp": {
    w: 1280,
    h: 638,
    srcset:
      "/posts/2025-0701-squid-game-3.640w.webp 640w, /posts/2025-0701-squid-game-3.960w.webp 960w, /posts/2025-0701-squid-game-3.webp 1280w",
    sizes:
      "(min-width: 1024px) 602px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0709-oppenheimer.webp": {
    w: 1280,
    h: 576,
    srcset:
      "/posts/2025-0709-oppenheimer.640w.webp 640w, /posts/2025-0709-oppenheimer.960w.webp 960w, /posts/2025-0709-oppenheimer.webp 1280w",
    sizes:
      "(min-width: 1024px) 667px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0729-the-northman.webp": {
    w: 1280,
    h: 544,
    srcset:
      "/posts/2025-0729-the-northman.640w.webp 640w, /posts/2025-0729-the-northman.960w.webp 960w, /posts/2025-0729-the-northman.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0802-the-stone.webp": {
    w: 1280,
    h: 534,
    srcset:
      "/posts/2025-0802-the-stone.640w.webp 640w, /posts/2025-0802-the-stone.960w.webp 960w, /posts/2025-0802-the-stone.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0810-weapons.webp": {
    w: 1280,
    h: 542,
    srcset:
      "/posts/2025-0810-weapons.640w.webp 640w, /posts/2025-0810-weapons.960w.webp 960w, /posts/2025-0810-weapons.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0813-death-stranding-2.webp": {
    w: 1280,
    h: 527,
    srcset:
      "/posts/2025-0813-death-stranding-2.640w.webp 640w, /posts/2025-0813-death-stranding-2.960w.webp 960w, /posts/2025-0813-death-stranding-2.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0816-bring-her-back.webp": {
    w: 1280,
    h: 640,
    srcset:
      "/posts/2025-0816-bring-her-back.640w.webp 640w, /posts/2025-0816-bring-her-back.960w.webp 960w, /posts/2025-0816-bring-her-back.webp 1280w",
    sizes:
      "(min-width: 1024px) 600px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0817-murder-mindfully.webp": {
    w: 1280,
    h: 640,
    srcset:
      "/posts/2025-0817-murder-mindfully.640w.webp 640w, /posts/2025-0817-murder-mindfully.960w.webp 960w, /posts/2025-0817-murder-mindfully.webp 1280w",
    sizes:
      "(min-width: 1024px) 600px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0824-a-quiet-place-day-one.webp": {
    w: 1280,
    h: 533,
    srcset:
      "/posts/2025-0824-a-quiet-place-day-one.640w.webp 640w, /posts/2025-0824-a-quiet-place-day-one.960w.webp 960w, /posts/2025-0824-a-quiet-place-day-one.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0830-final-destnation-bloodlines.webp": {
    w: 1280,
    h: 536,
    srcset:
      "/posts/2025-0830-final-destnation-bloodlines.640w.webp 640w, /posts/2025-0830-final-destnation-bloodlines.960w.webp 960w, /posts/2025-0830-final-destnation-bloodlines.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0907-clair-obscur-expedition-33.webp": {
    w: 1280,
    h: 536,
    srcset:
      "/posts/2025-0907-clair-obscur-expedition-33.640w.webp 640w, /posts/2025-0907-clair-obscur-expedition-33.960w.webp 960w, /posts/2025-0907-clair-obscur-expedition-33.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0919-past-lives.webp": {
    w: 1280,
    h: 694,
    srcset:
      "/posts/2025-0919-past-lives.640w.webp 640w, /posts/2025-0919-past-lives.960w.webp 960w, /posts/2025-0919-past-lives.webp 1280w",
    sizes:
      "(min-width: 1024px) 553px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0920-sideways.webp": {
    w: 1280,
    h: 699,
    srcset:
      "/posts/2025-0920-sideways.640w.webp 640w, /posts/2025-0920-sideways.960w.webp 960w, /posts/2025-0920-sideways.webp 1280w",
    sizes:
      "(min-width: 1024px) 549px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-0928-until-dawn.webp": {
    w: 1280,
    h: 632,
    srcset:
      "/posts/2025-0928-until-dawn.640w.webp 640w, /posts/2025-0928-until-dawn.960w.webp 960w, /posts/2025-0928-until-dawn.webp 1280w",
    sizes:
      "(min-width: 1024px) 608px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-1018-sinners.webp": {
    w: 1280,
    h: 465,
    srcset:
      "/posts/2025-1018-sinners.640w.webp 640w, /posts/2025-1018-sinners.960w.webp 960w, /posts/2025-1018-sinners.webp 1280w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-1109-casino-1.webp": {
    w: 1280,
    h: 695,
    srcset:
      "/posts/2025-1109-casino-1.640w.webp 640w, /posts/2025-1109-casino-1.960w.webp 960w, /posts/2025-1109-casino-1.webp 1280w",
    sizes:
      "(min-width: 1024px) 553px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2025-1109-casino-2.webp": {
    w: 1280,
    h: 694,
    srcset:
      "/posts/2025-1109-casino-2.640w.webp 640w, /posts/2025-1109-casino-2.960w.webp 960w, /posts/2025-1109-casino-2.webp 1280w",
    sizes:
      "(min-width: 1024px) 553px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-01-prachaniwet-market.webp": {
    w: 800,
    h: 533,
    srcset:
      "/posts/2026-0926-bangkok-flood-01-prachaniwet-market.640w.webp 640w, /posts/2026-0926-bangkok-flood-01-prachaniwet-market.webp 800w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-02-nawamin-road.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2026-0926-bangkok-flood-02-nawamin-road.640w.webp 640w, /posts/2026-0926-bangkok-flood-02-nawamin-road.960w.webp 960w, /posts/2026-0926-bangkok-flood-02-nawamin-road.webp 1280w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-03-phahon-yothin.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2026-0926-bangkok-flood-03-phahon-yothin.640w.webp 640w, /posts/2026-0926-bangkok-flood-03-phahon-yothin.960w.webp 960w, /posts/2026-0926-bangkok-flood-03-phahon-yothin.webp 1280w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.640w.webp 640w, /posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.960w.webp 960w, /posts/2026-0926-bangkok-flood-04-bang-kapi-intersection.webp 1280w",
    sizes:
      "(min-width: 1024px) 400px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-05-lat-phrao-41.webp": {
    w: 1280,
    h: 1707,
    srcset:
      "/posts/2026-0926-bangkok-flood-05-lat-phrao-41.640w.webp 640w, /posts/2026-0926-bangkok-flood-05-lat-phrao-41.960w.webp 960w, /posts/2026-0926-bangkok-flood-05-lat-phrao-41.webp 1280w",
    sizes:
      "(min-width: 1024px) 225px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-08-hero.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2026-0926-bangkok-flood-08-hero.640w.webp 640w, /posts/2026-0926-bangkok-flood-08-hero.960w.webp 960w, /posts/2026-0926-bangkok-flood-08-hero.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.640w.webp 640w, /posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.960w.webp 960w, /posts/2026-0926-bangkok-flood-09-phetchaburi-aerial.webp 1200w",
    sizes:
      "(min-width: 1024px) 573px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-11-phetchaburi-wading.webp": {
    w: 850,
    h: 567,
    srcset:
      "/posts/2026-0926-bangkok-flood-11-phetchaburi-wading.640w.webp 640w, /posts/2026-0926-bangkok-flood-11-phetchaburi-wading.webp 850w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-12-phetchaburi-scene.webp": {
    w: 850,
    h: 567,
    srcset:
      "/posts/2026-0926-bangkok-flood-12-phetchaburi-scene.640w.webp 640w, /posts/2026-0926-bangkok-flood-12-phetchaburi-scene.webp 850w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-13-bangkapi-community.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-13-bangkapi-community.640w.webp 640w, /posts/2026-0926-bangkok-flood-13-bangkapi-community.960w.webp 960w, /posts/2026-0926-bangkok-flood-13-bangkapi-community.webp 1200w",
    sizes:
      "(min-width: 1024px) 573px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.webp": {
    w: 850,
    h: 550,
    srcset:
      "/posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.640w.webp 640w, /posts/2026-0926-bangkok-flood-14-bangkapi-high-ground.webp 850w",
    sizes:
      "(min-width: 1024px) 464px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-15-muang-thong-thani.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-15-muang-thong-thani.640w.webp 640w, /posts/2026-0926-bangkok-flood-15-muang-thong-thani.960w.webp 960w, /posts/2026-0926-bangkok-flood-15-muang-thong-thani.webp 1200w",
    sizes:
      "(min-width: 1024px) 573px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-16-pm-boat-relief.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-16-pm-boat-relief.640w.webp 640w, /posts/2026-0926-bangkok-flood-16-pm-boat-relief.960w.webp 960w, /posts/2026-0926-bangkok-flood-16-pm-boat-relief.webp 1200w",
    sizes:
      "(min-width: 1024px) 573px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-17-market-wading.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/posts/2026-0926-bangkok-flood-17-market-wading.640w.webp 640w, /posts/2026-0926-bangkok-flood-17-market-wading.960w.webp 960w, /posts/2026-0926-bangkok-flood-17-market-wading.webp 1200w",
    sizes:
      "(min-width: 1024px) 573px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-18-tmd-forecast.webp": {
    w: 1280,
    h: 720,
    srcset:
      "/posts/2026-0926-bangkok-flood-18-tmd-forecast.640w.webp 640w, /posts/2026-0926-bangkok-flood-18-tmd-forecast.960w.webp 960w, /posts/2026-0926-bangkok-flood-18-tmd-forecast.webp 1280w",
    sizes:
      "(min-width: 1024px) 533px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-19-suvarnabhumi-luggage.webp": {
    w: 800,
    h: 533,
    srcset:
      "/posts/2026-0926-bangkok-flood-19-suvarnabhumi-luggage.640w.webp 640w, /posts/2026-0926-bangkok-flood-19-suvarnabhumi-luggage.webp 800w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-20-khlong-chan-aid.webp": {
    w: 800,
    h: 533,
    srcset:
      "/posts/2026-0926-bangkok-flood-20-khlong-chan-aid.640w.webp 640w, /posts/2026-0926-bangkok-flood-20-khlong-chan-aid.webp 800w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0926-bangkok-flood-21-bangkapi-market.webp": {
    w: 1280,
    h: 854,
    srcset:
      "/posts/2026-0926-bangkok-flood-21-bangkapi-market.640w.webp 640w, /posts/2026-0926-bangkok-flood-21-bangkapi-market.960w.webp 960w, /posts/2026-0926-bangkok-flood-21-bangkapi-market.webp 1280w",
    sizes:
      "(min-width: 1024px) 450px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0927-tales-of-arise-alphen-stats.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2026-0927-tales-of-arise-alphen-stats.640w.webp 640w, /posts/2026-0927-tales-of-arise-alphen-stats.960w.webp 960w, /posts/2026-0927-tales-of-arise-alphen-stats.webp 1280w",
    sizes:
      "(min-width: 1024px) 400px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0927-tales-of-arise-menu-lvl-100.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2026-0927-tales-of-arise-menu-lvl-100.640w.webp 640w, /posts/2026-0927-tales-of-arise-menu-lvl-100.960w.webp 960w, /posts/2026-0927-tales-of-arise-menu-lvl-100.webp 1280w",
    sizes:
      "(min-width: 1024px) 400px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0927-tales-of-arise-playtime.webp": {
    w: 1280,
    h: 960,
    srcset:
      "/posts/2026-0927-tales-of-arise-playtime.640w.webp 640w, /posts/2026-0927-tales-of-arise-playtime.960w.webp 960w, /posts/2026-0927-tales-of-arise-playtime.webp 1280w",
    sizes:
      "(min-width: 1024px) 400px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/2026-0927-tales-of-arise.webp": {
    w: 1280,
    h: 675,
    srcset:
      "/posts/2026-0927-tales-of-arise.640w.webp 640w, /posts/2026-0927-tales-of-arise.960w.webp 960w, /posts/2026-0927-tales-of-arise.webp 1280w",
    sizes:
      "(min-width: 1024px) 569px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/how-to-live-like-your-cat-thai-cover.webp": {
    w: 600,
    h: 871,
    srcset: "/posts/how-to-live-like-your-cat-thai-cover.webp 600w",
    sizes:
      "(min-width: 1024px) 207px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/how-to-live-like-your-cat.webp": {
    w: 1280,
    h: 1280,
    srcset:
      "/posts/how-to-live-like-your-cat.640w.webp 640w, /posts/how-to-live-like-your-cat.960w.webp 960w, /posts/how-to-live-like-your-cat.webp 1280w",
    sizes:
      "(min-width: 1024px) 300px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/the-bullet-journal-method-1.webp": {
    w: 1280,
    h: 890,
    srcset:
      "/posts/the-bullet-journal-method-1.640w.webp 640w, /posts/the-bullet-journal-method-1.960w.webp 960w, /posts/the-bullet-journal-method-1.webp 1280w",
    sizes:
      "(min-width: 1024px) 431px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/the-bullet-journal-method-2.webp": {
    w: 1280,
    h: 890,
    srcset:
      "/posts/the-bullet-journal-method-2.640w.webp 640w, /posts/the-bullet-journal-method-2.960w.webp 960w, /posts/the-bullet-journal-method-2.webp 1280w",
    sizes:
      "(min-width: 1024px) 431px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/the-power-of-output-1.webp": {
    w: 1280,
    h: 890,
    srcset:
      "/posts/the-power-of-output-1.640w.webp 640w, /posts/the-power-of-output-1.960w.webp 960w, /posts/the-power-of-output-1.webp 1280w",
    sizes:
      "(min-width: 1024px) 431px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/vscode-eslint-slow-error_msg.webp": {
    w: 800,
    h: 169,
    srcset:
      "/posts/vscode-eslint-slow-error_msg.640w.webp 640w, /posts/vscode-eslint-slow-error_msg.webp 800w",
    sizes:
      "(min-width: 1024px) 688px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
  "/posts/vscode-eslint-slow-slow_noti.webp": {
    w: 800,
    h: 407,
    srcset:
      "/posts/vscode-eslint-slow-slow_noti.640w.webp 640w, /posts/vscode-eslint-slow-slow_noti.webp 800w",
    sizes:
      "(min-width: 1024px) 590px, (min-width: 768px) 688px, calc(100vw - 72px)",
  },
};

export default photoMeta;
