// Generated by gen-photo-variants.ts — rerun after adding photos (pnpm gen-photos)
const photoMeta: Record<string, { w: number; h: number; srcset: string }> = {
  "/timecapsule/bangkok-flood-2026/01-prachaniwet-market.webp": {
    w: 800,
    h: 533,
    srcset:
      "/timecapsule/bangkok-flood-2026/01-prachaniwet-market.640w.webp 640w, /timecapsule/bangkok-flood-2026/01-prachaniwet-market.webp 800w",
  },
  "/timecapsule/bangkok-flood-2026/02-nawamin-road.webp": {
    w: 1500,
    h: 1000,
    srcset:
      "/timecapsule/bangkok-flood-2026/02-nawamin-road.640w.webp 640w, /timecapsule/bangkok-flood-2026/02-nawamin-road.960w.webp 960w, /timecapsule/bangkok-flood-2026/02-nawamin-road.webp 1500w",
  },
  "/timecapsule/bangkok-flood-2026/03-phahon-yothin.webp": {
    w: 1500,
    h: 1000,
    srcset:
      "/timecapsule/bangkok-flood-2026/03-phahon-yothin.640w.webp 640w, /timecapsule/bangkok-flood-2026/03-phahon-yothin.960w.webp 960w, /timecapsule/bangkok-flood-2026/03-phahon-yothin.webp 1500w",
  },
  "/timecapsule/bangkok-flood-2026/04-bang-kapi-intersection.webp": {
    w: 1500,
    h: 1125,
    srcset:
      "/timecapsule/bangkok-flood-2026/04-bang-kapi-intersection.640w.webp 640w, /timecapsule/bangkok-flood-2026/04-bang-kapi-intersection.960w.webp 960w, /timecapsule/bangkok-flood-2026/04-bang-kapi-intersection.webp 1500w",
  },
  "/timecapsule/bangkok-flood-2026/05-lat-phrao-41.webp": {
    w: 1500,
    h: 2000,
    srcset:
      "/timecapsule/bangkok-flood-2026/05-lat-phrao-41.640w.webp 640w, /timecapsule/bangkok-flood-2026/05-lat-phrao-41.960w.webp 960w, /timecapsule/bangkok-flood-2026/05-lat-phrao-41.webp 1500w",
  },
  "/timecapsule/bangkok-flood-2026/06-canal-pressure.webp": {
    w: 1300,
    h: 731,
    srcset:
      "/timecapsule/bangkok-flood-2026/06-canal-pressure.640w.webp 640w, /timecapsule/bangkok-flood-2026/06-canal-pressure.960w.webp 960w, /timecapsule/bangkok-flood-2026/06-canal-pressure.webp 1300w",
  },
  "/timecapsule/bangkok-flood-2026/07-bma-drainage.webp": {
    w: 1300,
    h: 731,
    srcset:
      "/timecapsule/bangkok-flood-2026/07-bma-drainage.640w.webp 640w, /timecapsule/bangkok-flood-2026/07-bma-drainage.960w.webp 960w, /timecapsule/bangkok-flood-2026/07-bma-drainage.webp 1300w",
  },
  "/timecapsule/bangkok-flood-2026/08-hero.webp": {
    w: 1300,
    h: 731,
    srcset:
      "/timecapsule/bangkok-flood-2026/08-hero.640w.webp 640w, /timecapsule/bangkok-flood-2026/08-hero.960w.webp 960w, /timecapsule/bangkok-flood-2026/08-hero.webp 1300w",
  },
  "/timecapsule/bangkok-flood-2026/09-phetchaburi-aerial.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/timecapsule/bangkok-flood-2026/09-phetchaburi-aerial.640w.webp 640w, /timecapsule/bangkok-flood-2026/09-phetchaburi-aerial.960w.webp 960w, /timecapsule/bangkok-flood-2026/09-phetchaburi-aerial.webp 1200w",
  },
  "/timecapsule/bangkok-flood-2026/11-phetchaburi-wading.webp": {
    w: 850,
    h: 567,
    srcset:
      "/timecapsule/bangkok-flood-2026/11-phetchaburi-wading.640w.webp 640w, /timecapsule/bangkok-flood-2026/11-phetchaburi-wading.webp 850w",
  },
  "/timecapsule/bangkok-flood-2026/12-phetchaburi-scene.webp": {
    w: 850,
    h: 567,
    srcset:
      "/timecapsule/bangkok-flood-2026/12-phetchaburi-scene.640w.webp 640w, /timecapsule/bangkok-flood-2026/12-phetchaburi-scene.webp 850w",
  },
  "/timecapsule/bangkok-flood-2026/13-bangkapi-community.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/timecapsule/bangkok-flood-2026/13-bangkapi-community.640w.webp 640w, /timecapsule/bangkok-flood-2026/13-bangkapi-community.960w.webp 960w, /timecapsule/bangkok-flood-2026/13-bangkapi-community.webp 1200w",
  },
  "/timecapsule/bangkok-flood-2026/14-bangkapi-high-ground.webp": {
    w: 850,
    h: 550,
    srcset:
      "/timecapsule/bangkok-flood-2026/14-bangkapi-high-ground.640w.webp 640w, /timecapsule/bangkok-flood-2026/14-bangkapi-high-ground.webp 850w",
  },
  "/timecapsule/bangkok-flood-2026/15-muang-thong-thani.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/timecapsule/bangkok-flood-2026/15-muang-thong-thani.640w.webp 640w, /timecapsule/bangkok-flood-2026/15-muang-thong-thani.960w.webp 960w, /timecapsule/bangkok-flood-2026/15-muang-thong-thani.webp 1200w",
  },
  "/timecapsule/bangkok-flood-2026/16-pm-boat-relief.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/timecapsule/bangkok-flood-2026/16-pm-boat-relief.640w.webp 640w, /timecapsule/bangkok-flood-2026/16-pm-boat-relief.960w.webp 960w, /timecapsule/bangkok-flood-2026/16-pm-boat-relief.webp 1200w",
  },
  "/timecapsule/bangkok-flood-2026/17-market-wading.webp": {
    w: 1200,
    h: 628,
    srcset:
      "/timecapsule/bangkok-flood-2026/17-market-wading.640w.webp 640w, /timecapsule/bangkok-flood-2026/17-market-wading.960w.webp 960w, /timecapsule/bangkok-flood-2026/17-market-wading.webp 1200w",
  },
};

export default photoMeta;
