import { execSync } from "child_process";
import fs from "fs";
import path from "path";

import { format as oxfmt } from "oxfmt";

const WIDTHS = [640, 960];
const QUALITY = 55;
const MAX_BASE_WIDTH = 1280; // ponytail: 3x phones pick the base file; cap it so they don't fetch 1500w
// Rendered widths from Markdown.tsx img (w-full / lg:w-auto lg:max-h-[300px]); 688 = timecapsule
// column (768 - px-5 - p-5), posts' prose column is ~40px narrower — never more than one rung off
const DESKTOP_MAX_W = 688;
const DESKTOP_MAX_H = 300;

function renderedSizes(w: number, h: number) {
  const desktopW = Math.min(DESKTOP_MAX_W, Math.round((DESKTOP_MAX_H * w) / h));
  return `(min-width: 1024px) ${desktopW}px, (min-width: 768px) ${DESKTOP_MAX_W}px, calc(100vw - 72px)`;
}
const PUBLIC_DIR = path.join(process.cwd(), "public", "posts");
const OUT_FILE = path.join(
  process.cwd(),
  "app",
  "timecapsule",
  "photo-meta.ts",
);

function imageDims(file: string) {
  const out = execSync(
    `sips -g pixelWidth -g pixelHeight ${JSON.stringify(file)}`,
  ).toString();
  return {
    w: Number(/pixelWidth: (\d+)/.exec(out)?.[1]),
    h: Number(/pixelHeight: (\d+)/.exec(out)?.[1]),
  };
}

const meta: Record<
  string,
  {
    w: number;
    h: number;
    srcset: string;
    sizes: string;
  }
> = {};

async function main() {
  for (const file of fs.readdirSync(PUBLIC_DIR)) {
    if (!file.endsWith(".webp") || /\.\d+w\.webp$/.test(file)) continue;
    const full = path.join(PUBLIC_DIR, file);
    const { w: origW } = imageDims(full);
    if (origW > MAX_BASE_WIDTH) {
      // encode once; reruns must not re-encode (q55 -> q55 generation loss + binary churn)
      const tmp = `${full}.tmp.webp`;
      execSync(
        `cwebp -q ${QUALITY} -resize ${MAX_BASE_WIDTH} 0 -quiet ${JSON.stringify(full)} -o ${JSON.stringify(tmp)}`,
      );
      fs.renameSync(tmp, full);
    }
    const { w, h } = imageDims(full);
    const src = `/posts/${file}`;
    const candidates: string[] = [];
    for (const width of WIDTHS) {
      if (w <= width) continue;
      const variantFile = path.join(
        PUBLIC_DIR,
        `${file.replace(/\.webp$/, "")}.${width}w.webp`,
      );
      if (!fs.existsSync(variantFile)) {
        execSync(
          `cwebp -q ${QUALITY} -resize ${width} 0 -quiet ${JSON.stringify(full)} -o ${JSON.stringify(variantFile)}`,
        );
      }
      candidates.push(`${src.replace(/\.webp$/, "")}.${width}w.webp ${width}w`);
    }
    candidates.push(`${src} ${w}w`);
    meta[src] = {
      w,
      h,
      srcset: candidates.join(", "),
      sizes: renderedSizes(w, h),
    };
  }

  const source =
    `// Generated by gen-photo-variants.ts — rerun after adding photos (pnpm gen-photos)\n` +
    `const photoMeta: Record<string, { w: number; h: number; srcset: string; sizes: string }> = ${JSON.stringify(meta, null, 2)};\n\nexport default photoMeta;\n`;
  // ponytail: API skips .oxfmtrc.json — inline the one non-default option; keep in sync if .oxfmtrc.json changes
  fs.writeFileSync(
    OUT_FILE,
    (await oxfmt(OUT_FILE, source, { printWidth: 80 })).code,
  );
  console.log(
    `Wrote ${Object.keys(meta).length} entries to ${path.relative(process.cwd(), OUT_FILE)}`,
  );
}

void main();
