import { execSync } from "child_process";
import fs from "fs";
import path from "path";

import prettier from "prettier";

const WIDTHS = [640, 960];
const QUALITY = 55;
const MAX_BASE_WIDTH = 1280; // ponytail: 3x phones pick the base file; cap it so they don't fetch 1500w
const PUBLIC_DIR = path.join(process.cwd(), "public", "timecapsule");
const OUT_FILE = path.join(process.cwd(), "app", "timecapsule", "photo-meta.ts");

function imageDims(file: string) {
  const out = execSync(
    `sips -g pixelWidth -g pixelHeight ${JSON.stringify(file)}`,
  ).toString();
  return {
    w: Number(/pixelWidth: (\d+)/.exec(out)?.[1]),
    h: Number(/pixelHeight: (\d+)/.exec(out)?.[1]),
  };
}

const meta: Record<string, { w: number; h: number; srcset: string }> = {};

async function main() {
  for (const dir of fs.readdirSync(PUBLIC_DIR, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;
    const folder = path.join(PUBLIC_DIR, dir.name);
    for (const file of fs.readdirSync(folder)) {
      if (!file.endsWith(".webp") || /\.\d+w\.webp$/.test(file)) continue;
      const full = path.join(folder, file);
      const { w: origW } = imageDims(full);
      const tmp = `${full}.tmp.webp`;
      execSync(
        `cwebp -q ${QUALITY} -resize ${Math.min(origW, MAX_BASE_WIDTH)} 0 -quiet ${JSON.stringify(full)} -o ${JSON.stringify(tmp)}`,
      );
      fs.renameSync(tmp, full);
      const { w, h } = imageDims(full);
      const src = `/timecapsule/${dir.name}/${file}`;
      const candidates: string[] = [];
      for (const width of WIDTHS) {
        if (w <= width) continue;
        const variantFile = path.join(
          folder,
          `${file.replace(/\.webp$/, "")}.${width}w.webp`,
        );
        execSync(
          `cwebp -q ${QUALITY} -resize ${width} 0 -quiet ${JSON.stringify(full)} -o ${JSON.stringify(variantFile)}`,
        );
        candidates.push(`${src.replace(/\.webp$/, "")}.${width}w.webp ${width}w`);
      }
      candidates.push(`${src} ${w}w`);
      meta[src] = { w, h, srcset: candidates.join(", ") };
    }
  }

  const source =
    `// Generated by gen-photo-variants.ts — rerun after adding photos (pnpm gen-photos)\n` +
    `const photoMeta: Record<string, { w: number; h: number; srcset: string }> = ${JSON.stringify(meta, null, 2)};\n\nexport default photoMeta;\n`;
  fs.writeFileSync(
    OUT_FILE,
    await prettier.format(source, { parser: "typescript" }),
  );
  console.log(
    `Wrote ${Object.keys(meta).length} entries to ${path.relative(process.cwd(), OUT_FILE)}`,
  );
}

void main();
