name: Static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Lint
        run: pnpm run lint
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Lint
        run: pnpm run tsc
