name: Static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm ci
      - name: Lint
        run: npm run lint
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm ci
      - name: Lint
        run: npm run tsc
